name: Docker Builder (Test)

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
  workflow_dispatch:
  schedule:
    # Runs Everyday at 02:00 UTC
    - cron: '0 2 * * *'

concurrency:
  group: ci-base-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      platform: "linux/amd64"
      DockerID: "archy-base"

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: 'main'
      - name: Enable KVM group perms [Experimental]
        run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' \
              | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm
      - name: Minor Disc Cleanup [Optinal]
        run: |
          docker system prune -a -f
          sudo rm -rf /usr/local/lib/android /opt/hostedtoolcache \
            /usr/local/share/vcpkg /usr/share/dotnet /opt/ghc
      - name: Login to Docker [Hub]
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU [Optional]
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - name: Docker Metadata action
        id: docker_meta_native
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/${{ env.DockerID }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,enable=true,prefix=sha-,format=short
            type=raw,value={{date 'YY.MM.DDDD.HHmm' tz='Asia/Dhaka'}},enable=true
      - name: Build & Push the Docker image
        id: docker_build_native
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: true
          DOCKER_BUILD_RECORD_UPLOAD: true
        with:
          allow: security.insecure
          context: .
          file: Dockerfile
          platforms: ${{ env.platform }}
          push: true
          provenance: false
          tags: ${{ steps.docker_meta_native.outputs.tags }}
          labels: |
            maintainer="fr3akyphantom <rokibhasansagar2014@outlook.com>"
            org.opencontainers.image.authors="fr3akyphantom <rokibhasansagar2014@outlook.com>"
            org.opencontainers.image.licenses=MIT
          outputs: type=registry
      - name: Image digest (Native)
        run: echo ${{ steps.docker_build_native.outputs.digest }}

